init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/1a414a5a94b6c2750022
    on_build_success: false
    on_build_failure: true